<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccommodationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('accommodations')->insert([
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'HOTEL TRANSCAM',
                'description' => '',
                'latitude' => 7.3107306,
                'longitude' => 13.5726739,
                'promoter' => 'Société hôtelière du Nord Cameroun',
                'number_of_stars' => 3,
                'number_of_rooms' => 50,
                'number_of_beds' => 50,
                'restaurant_capacity' => 100,
                'bar_capacity' =>20,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '22251252/99923280 resahoteltranscam@yayoo.fr',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'HOTEL MENTONG PALACE',
                'description' => '',
                'latitude' => 7.3322358,
                'longitude' => 13.5705014,
                'promoter' => 'MENTONG A KIKI',
                'number_of_stars' => 2,
                'number_of_rooms' => 26,
                'number_of_beds' => 26,
                'restaurant_capacity' => 40,
                'bar_capacity' =>40,
                'conference_room_capacity' => 200,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99529907/96747766 hotelmentongpalace@yahoo.fr',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'NICE HOTEL',
                'description' => '',
                'latitude' => 7.3382009,
                'longitude' => 13.5621952,
                'promoter' => 'BABBA Hamadama',
                'number_of_stars' => 2,
                'number_of_rooms' => 18,
                'number_of_beds' => 22,
                'restaurant_capacity' => 40,
                'bar_capacity' =>40,
                'conference_room_capacity' => 50,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99692355/75507523 nicehotel@hotmail.fr',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'HOTEL RELAIS SAVEUR',
                'description' => '',
                'latitude' => 9.4518194,
                'longitude' => 13.0294229,
                'promoter' => 'DJIYA Elie',
                'number_of_stars' => 2,
                'number_of_rooms' => 32,
                'number_of_beds' => 32,
                'restaurant_capacity' => 30,
                'bar_capacity' => 30,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99708115',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'FAMILY CITY MOTEL',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'Mme NOUTSA',
                'number_of_stars' => 1,
                'number_of_rooms' => 20,
                'number_of_beds' => 20,
                'restaurant_capacity' => 20,
                'bar_capacity' => 20,
                'conference_room_capacity' => 50,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '74859289',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'HOTEL FETY',
                'description' => '',
                'latitude' => 7.3360403,
                'longitude' => 13.5677499,
                'promoter' => 'FEUZEU Jonas',
                'number_of_stars' => 1,
                'number_of_rooms' => 18,
                'number_of_beds' => 18,
                'restaurant_capacity' => 25,
                'bar_capacity' => 25,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '22252380/74312818',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'HOTEL DU LAC',
                'description' => '',
                'latitude' => 7.3381956,
                'longitude' => 5.1293086,
                'promoter' => 'TCHIAKOUA Michel',
                'number_of_stars' => 1,
                'number_of_rooms' => 12,
                'number_of_beds' => 12,
                'restaurant_capacity' => 24,
                'bar_capacity' => 24,
                'conference_room_capacity' => 100,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => 'hoteldulac_ndere@yahoo.fr 99528221/99870377',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'HOTEL VINA',
                'description' => '',
                'latitude' => 7.3223451,
                'longitude' => 13.5723166,
                'promoter' => 'ALHADJI Ibrahima',
                'number_of_stars' => 1,
                'number_of_rooms' => 14,
                'number_of_beds' => 14,
                'restaurant_capacity' => 25,
                'bar_capacity' => 25,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => 'wwwhotelvina.com 22036043/77542973',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'HOTEL DE LA GARE',
                'description' => '',
                'latitude' => 7.3223716,
                'longitude' => 13.5645917,
                'promoter' => 'AHMADOU Abdourahman',
                'number_of_stars' => 1,
                'number_of_rooms' => 18,
                'number_of_beds' => 18,
                'restaurant_capacity' => 20,
                'bar_capacity' => 20,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => 'Amor_isaac@yahoo.fr 99803680/22252217',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'HOTEL LA MENOUA',
                'description' => '',
                'latitude' => 7.3270586,
                'longitude' => 13.5751968,
                'promoter' => 'DOGMO Pierre',
                'number_of_stars' => 1,
                'number_of_rooms' => 15,
                'number_of_beds' => 15,
                'restaurant_capacity' => 40,
                'bar_capacity' => 30,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99850787',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'MOTEL MARHABA',
                'description' => '',
                'latitude' => 7.3196389,
                'longitude' => 13.5719884,
                'promoter' => 'SANDJO Emmanuel',
                'number_of_stars' => 1,
                'number_of_rooms' => 10,
                'number_of_beds' => 11,
                'restaurant_capacity' => 100,
                'bar_capacity' => 100,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77549990/99768558',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'HOTEL POSADA STYLE',
                'description' => '',
                'latitude' => 7.3245106,
                'longitude' => 13.568866,
                'promoter' => 'DJOMO Ndjelankon Henri',
                'number_of_stars' => 1,
                'number_of_rooms' => 32,
                'number_of_beds' => 32,
                'restaurant_capacity' => 40,
                'bar_capacity' => 20,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99854454/96492675',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'HOTEL LES ALIZES',
                'description' => '',
                'latitude' => 7.3286491,
                'longitude' => 13.5832641,
                'promoter' => 'ESSOH Alphonse',
                'number_of_stars' => 1,
                'number_of_rooms' => 11,
                'number_of_beds' => 11,
                'restaurant_capacity' => 20,
                'bar_capacity' => 18,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77437021',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'RANCH DE NGAOUNDABA',
                'description' => '',
                'latitude' => 7.1342267,
                'longitude' => 13.6938217,
                'promoter' => 'Fermé momentanément',
                'number_of_stars' => 1,
                'number_of_rooms' => 19,
                'number_of_beds' => 32,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'HOTEL PAKEM PALACE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'MBEUMO Alphonse',
                'number_of_stars' => null,
                'number_of_rooms' => 18,
                'number_of_beds' => 18,
                'restaurant_capacity' => 30,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99860907',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'AL HERR HOTEL',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'SANDJO Emmanuel',
                'number_of_stars' => null,
                'number_of_rooms' => 15,
                'number_of_beds' => 15,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77549990',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 6,
                'name' => 'AUBERGE LADACO',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'LENGUE Daniel',
                'number_of_stars' => null,
                'number_of_rooms' => 14,
                'number_of_beds' => 14,
                'restaurant_capacity' => 20,
                'bar_capacity' => 20,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '70309993',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'MOTEL LA REFERENCE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'ATEH NGWA Glory',
                'number_of_stars' => null,
                'number_of_rooms' => 14,
                'number_of_beds' => 14,
                'restaurant_capacity' => 10,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '75288250/99860909',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'HOTEL TERMINUS',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'KAMDEM Emmanuel',
                'number_of_stars' => null,
                'number_of_rooms' => 5,
                'number_of_beds' => 5,
                'restaurant_capacity' => 20,
                'bar_capacity' => 18,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '76259343',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 6,
                'name' => 'AUBERGE AL HILAL',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'BABBA Hamadama',
                'number_of_stars' => null,
                'number_of_rooms' => 5,
                'number_of_beds' => 5,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '75507523/99692355',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 6,
                'name' => 'AUBERGE LA CITE',
                'description' => '',
                'latitude' => 9.298216,
                'longitude' => 9.1712054,
                'promoter' => 'KAMDEM E.',
                'number_of_stars' => null,
                'number_of_rooms' => 8,
                'number_of_beds' => 8,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99843942',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 6,
                'name' => 'AUBERGE L’ETOILE',
                'description' => '',
                'latitude' => 7.3354452,
                'longitude' => 13.5604339,
                'promoter' => 'SIMEU Michel',
                'number_of_stars' => null,
                'number_of_rooms' => 16,
                'number_of_beds' => 16,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '75746139',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 6,
                'name' => 'AUBERGE APHRODITE I',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'NZEUBOU Daniel',
                'number_of_stars' => null,
                'number_of_rooms' => 6,
                'number_of_beds' => 6,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99617963',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 6,
                'name' => 'AUBERGE LA CONCORDE',
                'description' => '',
                'latitude' => 6.5938246,
                'longitude' => 9.8546334,
                'promoter' => 'MABOU',
                'number_of_stars' => null,
                'number_of_rooms' => 18,
                'number_of_beds' => 18,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77594218/99680111',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 6,
                'name' => 'AUBERGE LE REFUGE',
                'description' => '',
                'latitude' => 7.3277837,
                'longitude' => 13.5615713,
                'promoter' => 'WABOU Jean',
                'number_of_stars' => null,
                'number_of_rooms' => 6,
                'number_of_beds' => 6,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '76259343',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 6,
                'name' => 'AUBERGE PRESTIGE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'TIENTCHEU',
                'number_of_stars' => null,
                'number_of_rooms' => 10,
                'number_of_beds' => 10,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99652384',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 6,
                'name' => 'AUBERGE WEE GARA',
                'description' => '',
                'latitude' => 6.8379386,
                'longitude' => 14.6887576,
                'promoter' => 'AOUDOU Hamayadji',
                'number_of_stars' => null,
                'number_of_rooms' => 7,
                'number_of_beds' => 7,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77912635',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 6,
                'name' => 'AUBERGE TOUJOURS PROPRE',
                'description' => '',
                'latitude' => 7.3308302,
                'longitude' => 13.5703821,
                'promoter' => 'OBINA Nwakwo Joseph',
                'number_of_stars' => null,
                'number_of_rooms' => 10,
                'number_of_beds' => 10,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77257924',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 6,
                'name' => 'AUBERGE GIRAFE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => null,
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 1,
                'name' => 'BEL HOTEL',
                'description' => '',
                'latitude' => 7.3382009,
                'longitude' => 13.5621952,
                'promoter' => 'ALHADJI Bello',
                'number_of_stars' => null,
                'number_of_rooms' => 30,
                'number_of_beds' => 30,
                'restaurant_capacity' => null,
                'bar_capacity' => 20,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '74140486/99861080',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE ADAMAOUA',
                'description' => '',
                'latitude' => 7.3381956,
                'longitude' => 13.5626887,
                'promoter' => 'AWA Muluh',
                'number_of_stars' => null,
                'number_of_rooms' => 8,
                'number_of_beds' => 8,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77345908',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE BEAU SEJOUR',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'YONKEU Albert',
                'number_of_stars' => null,
                'number_of_rooms' => 15,
                'number_of_beds' => 15,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77437565',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE CALYPSO',
                'description' => '',
                'latitude' => 6.4649923,
                'longitude' => 12.6178229,
                'promoter' => 'Mme KUIPO',
                'number_of_stars' => null,
                'number_of_rooms' => 19,
                'number_of_beds' => 19,
                'restaurant_capacity' => 60,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '75172547',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE LE DJEREM',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'BOYOM Joseph',
                'number_of_stars' => null,
                'number_of_rooms' => 10,
                'number_of_beds' => 10,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77807485',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE LE LIDO',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'KHAN Samuel',
                'number_of_stars' => null,
                'number_of_rooms' => 13,
                'number_of_beds' => 13,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77243141',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE NOUVELLE VIE TRANQUILLE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'KALLA Elie',
                'number_of_stars' => null,
                'number_of_rooms' => 10,
                'number_of_beds' => 10,
                'restaurant_capacity' => 70,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE TEUFANG',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'NIKOU August',
                'number_of_stars' => null,
                'number_of_rooms' => 10,
                'number_of_beds' => 10,
                'restaurant_capacity' => 60,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '74517309',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE AMBASSADE DU NDE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'NGASSA Jean',
                'number_of_stars' => null,
                'number_of_rooms' => 8,
                'number_of_beds' => 8,
                'restaurant_capacity' => 60,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '75021488',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE CALIFORNIA',
                'description' => '',
                'latitude' => 6.448161,
                'longitude' => 13.2707049,
                'promoter' => 'VILDINA A.',
                'number_of_stars' => null,
                'number_of_rooms' => 19,
                'number_of_beds' => 19,
                'restaurant_capacity' => 30,
                'bar_capacity' => 30,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '96937616',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE LE CHATEAU',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'Mme TIOFACK E',
                'number_of_stars' => null,
                'number_of_rooms' => 8,
                'number_of_beds' => 8,
                'restaurant_capacity' => 15,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE MODESTIE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'BARBA K.',
                'number_of_stars' => null,
                'number_of_rooms' => 8,
                'number_of_beds' => 8,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77790709',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE MONT NGAOUNDAL',
                'description' => '',
                'latitude' => 6.4602777,
                'longitude' => 13.249018,
                'promoter' => 'NGASSA',
                'number_of_stars' => null,
                'number_of_rooms' => 9,
                'number_of_beds' => 9,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '75021488',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE LA VICTOIRE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'MONDJA Olivier',
                'number_of_stars' => null,
                'number_of_rooms' => 14,
                'number_of_beds' => 14,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '79828072',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE INTER',
                'description' => '',
                'latitude' => 6.470326,
                'longitude' => 11.5640631,
                'promoter' => 'KAMMOGNE Pierre',
                'number_of_stars' => null,
                'number_of_rooms' => 8,
                'number_of_beds' => 8,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77414375',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 1,
                'name' => 'HOTEL Le Bien Etre',
                'description' => '',
                'latitude' => 6.4699091,
                'longitude' => 9.5803081,
                'promoter' => 'BIDIM Barthélemy',
                'number_of_stars' => null,
                'number_of_rooms' => 14,
                'number_of_beds' => 14,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '94660136',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 1,
                'name' => 'MOTEL Le Partenaire',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'Me DJOFACK',
                'number_of_stars' => null,
                'number_of_rooms' => 14,
                'number_of_beds' => 14,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE Le Transitaire',
                'description' => '',
                'latitude' => 6.4743214,
                'longitude' => 13.2611086,
                'promoter' => 'Me FONGANG',
                'number_of_stars' => null,
                'number_of_rooms' => 11,
                'number_of_beds' => 15,
                'restaurant_capacity' => 40,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77781806',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 6,
                'name' => 'AUBERGE Nid d’Or',
                'description' => '',
                'latitude' => 6.4461601,
                'longitude' => 13.272977,
                'promoter' => 'MEDOUGA',
                'number_of_stars' => null,
                'number_of_rooms' => 12,
                'number_of_beds' => 12,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77571745',
                'website' => null
            ],
            [
                'department_id' => 4,
                'type' => 6,
                'name' => 'AUBERGE MANDELA',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'FOGUE Janvier',
                'number_of_stars' => null,
                'number_of_rooms' => 15,
                'number_of_beds' => 15,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'type' => 6,
                'name' => 'AUBERGE JEUNESSE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'MAMADOU D.',
                'number_of_stars' => null,
                'number_of_rooms' => 10,
                'number_of_beds' => 10,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'type' => 6,
                'name' => 'AUBERGE SAFARI',
                'description' => '',
                'latitude' => 5.5841091,
                'longitude' => 9.3614816,
                'promoter' => 'YOMBI R.',
                'number_of_stars' => null,
                'number_of_rooms' => 8,
                'number_of_beds' => 8,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'type' => 6,
                'name' => 'AUBERGE CENTRE SOCIO',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'EELC',
                'number_of_stars' => null,
                'number_of_rooms' => 19,
                'number_of_beds' => 40,
                'restaurant_capacity' => 200,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'type' => 6,
                'name' => 'AUBERGE LA CHALEUR',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'AOUDOU H.',
                'number_of_stars' => null,
                'number_of_rooms' => 5,
                'number_of_beds' => 5,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'type' => 6,
                'name' => 'AUBERGE BIEN EST BIEN',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'FEKOU M.',
                'number_of_stars' => null,
                'number_of_rooms' => 13,
                'number_of_beds' => 13,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'type' => 6,
                'name' => 'AUBERGE RENAISSANCE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'KONTCHOU F.',
                'number_of_stars' => null,
                'number_of_rooms' => 6,
                'number_of_beds' => 6,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'type' => 6,
                'name' => 'AUBERGE DA’TOU',
                'description' => '',
                'latitude' => 6.5163656,
                'longitude' => 14.275425,
                'promoter' => 'AMADOU Paul',
                'number_of_stars' => null,
                'number_of_rooms' => 14,
                'number_of_beds' => 14,
                'restaurant_capacity' => 50,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'type' => 6,
                'name' => 'AUBERGE SILVANO',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'ABOU',
                'number_of_stars' => null,
                'number_of_rooms' => 8,
                'number_of_beds' => 8,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'type' => 6,
                'name' => 'AUBERGE DU PEUPLE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'ABOU',
                'number_of_stars' => null,
                'number_of_rooms' => 5,
                'number_of_beds' => 5,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'type' => 6,
                'name' => 'AUBERGE DE L’ESPOIR',
                'description' => '',
                'latitude' => 6.4026507,
                'longitude' => 11.3133749,
                'promoter' => null,
                'number_of_stars' => null,
                'number_of_rooms' => 8,
                'number_of_beds' => 8,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'type' => 6,
                'name' => 'AUBERGE SAMBA',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'BAA PORO',
                'number_of_stars' => null,
                'number_of_rooms' => 7,
                'number_of_beds' => 7,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'type' => 6,
                'name' => 'AUBERGE AMSANOU',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'AMSANOU',
                'number_of_stars' => null,
                'number_of_rooms' => 10,
                'number_of_beds' => 10,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE LA POSADA',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'BADJANG J.',
                'number_of_stars' => null,
                'number_of_rooms' => 17,
                'number_of_beds' => 17,
                'restaurant_capacity' => 40,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE DEMOCRATIQUE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'YOGAP Benoît',
                'number_of_stars' => null,
                'number_of_rooms' => 19,
                'number_of_beds' => 19,
                'restaurant_capacity' => 25,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE ESCALE DU NORD',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'KAMDEM K.',
                'number_of_stars' => null,
                'number_of_rooms' => 12,
                'number_of_beds' => 12,
                'restaurant_capacity' => 100,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE ETOILE',
                'description' => '',
                'latitude' => 7.3354452,
                'longitude' => 13.5604339,
                'promoter' => 'ASSANA Nana',
                'number_of_stars' => null,
                'number_of_rooms' => 19,
                'number_of_beds' => 19,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE LE KIMI',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'OUMAROU D.',
                'number_of_stars' => null,
                'number_of_rooms' => 12,
                'number_of_beds' => 12,
                'restaurant_capacity' => 50,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE LE NYAMBOYA',
                'description' => '',
                'latitude' => 6.2867868,
                'longitude' => 11.5759992,
                'promoter' => 'MAKEM Théo',
                'number_of_stars' => null,
                'number_of_rooms' => 8,
                'number_of_beds' => 8,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE LE RADIAN',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'Mme KUMI O.',
                'number_of_stars' => null,
                'number_of_rooms' => 5,
                'number_of_beds' => 5,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE LE SARE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'BADJANG J.',
                'number_of_stars' => null,
                'number_of_rooms' => 15,
                'number_of_beds' => 15,
                'restaurant_capacity' => 30,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE MBOUDA',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'LAPPA Fr.',
                'number_of_stars' => null,
                'number_of_rooms' => 18,
                'number_of_beds' => 18,
                'restaurant_capacity' => 60,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE MICHEL',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'KANDOU M.',
                'number_of_stars' => null,
                'number_of_rooms' => 8,
                'number_of_beds' => 8,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE COMPLEXE SEM SEM',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'MOUMBIOU',
                'number_of_stars' => null,
                'number_of_rooms' => 4,
                'number_of_beds' => 4,
                'restaurant_capacity' => 70,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE COMPLEXE FATI',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'FATI Joseph',
                'number_of_stars' => null,
                'number_of_rooms' => 15,
                'number_of_beds' => 15,
                'restaurant_capacity' => 60,
                'bar_capacity' => 6,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE DE L’ESPOIR',
                'description' => '',
                'latitude' => 6.4026507,
                'longitude' => 11.3154134,
                'promoter' => 'IBRAHIM Y.',
                'number_of_stars' => null,
                'number_of_rooms' => 20,
                'number_of_beds' => 20,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE LE MEMAL',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'NGAH N.',
                'number_of_stars' => null,
                'number_of_rooms' => 11,
                'number_of_beds' => 11,
                'restaurant_capacity' => 30,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE AMPOULE ROUGE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => null,
                'number_of_stars' => null,
                'number_of_rooms' => 6,
                'number_of_beds' => 6,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE LE PARADIS',
                'description' => '',
                'latitude' => 5.2106792,
                'longitude' => 8.5222251,
                'promoter' => 'DJOUTELE J.',
                'number_of_stars' => null,
                'number_of_rooms' => 27,
                'number_of_beds' => 27,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE LE KOUZA',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'MOUICHE M.',
                'number_of_stars' => null,
                'number_of_rooms' => 15,
                'number_of_beds' => 15,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'AUBERGE PAPA LEON',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'Mme TAGNE',
                'number_of_stars' => null,
                'number_of_rooms' => 17,
                'number_of_beds' => 17,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'type' => 6,
                'name' => 'NOUVELLE AUBERGE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'NOUMTECHE',
                'number_of_stars' => null,
                'number_of_rooms' => 18,
                'number_of_beds' => 18,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 5,
                'type' => 6,
                'name' => 'AUBERGE MUNICIPALE',
                'description' => '',
                'latitude' => 7.0894948,
                'longitude' => 12.4745661,
                'promoter' => 'Commune de Tignère',
                'number_of_stars' => null,
                'number_of_rooms' => 13,
                'number_of_beds' => 13,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '75407422',
                'website' => null
            ],
            [
                'department_id' => 5,
                'type' => 6,
                'name' => 'AUBERGE DE LA VALLEE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'BABA BAMBATI',
                'number_of_stars' => null,
                'number_of_rooms' => 14,
                'number_of_beds' => 14,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99240916',
                'website' => null
            ],
            [
                'department_id' => 5,
                'type' => 6,
                'name' => 'AUBERGE LE REPOSOIR',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'Mme BAHAOUA',
                'number_of_stars' => null,
                'number_of_rooms' => 4,
                'number_of_beds' => 4,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 5,
                'type' => 6,
                'name' => 'AUBERGE MUNICIPALE',
                'description' => '',
                'latitude' => 7.0894948,
                'longitude' => 12.4745661,
                'promoter' => 'Commune de Kontcha',
                'number_of_stars' => null,
                'number_of_rooms' => 10,
                'number_of_beds' => 10,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 5,
                'type' => 1,
                'name' => 'ACCUEIL SAINT JOSEPH',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'Mission Catholique',
                'number_of_stars' => null,
                'number_of_rooms' => 6,
                'number_of_beds' => 6,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99467983',
                'website' => null
            ],
            [
                'department_id' => 5,
                'type' => 6,
                'name' => 'AUBERGE ESCALE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'NGUESSOM',
                'number_of_stars' => null,
                'number_of_rooms' => 8,
                'number_of_beds' => 8,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '96009954',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'REST. TRANSCAM',
                'description' => '',
                'latitude' => 7.3106694,
                'longitude' => 13.5725329,
                'promoter' => 'SHNC',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 100,
                'bar_capacity' => 20,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99923280',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'REST. NICE HOTEL',
                'description' => '',
                'latitude' => 7.3382009,
                'longitude' => 13.5621952,
                'promoter' => 'BABBA Hamadama',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 40,
                'bar_capacity' => 40,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '75507523/99692355',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'REST. HOTEL RELAIS SAVEUR',
                'description' => '',
                'latitude' => 9.4518194,
                'longitude' => 13.0294229,
                'promoter' => 'DJIYA Elie',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 30,
                'bar_capacity' => 30,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99708115',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'REST. HOTEL DU LAC',
                'description' => '',
                'latitude' => 7.3381956,
                'longitude' => 5.1293086,
                'promoter' => 'TCHIAKOUA Michel',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 24,
                'bar_capacity' => 24,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99528221/99870377',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'COMPLEXE MARHABA',
                'description' => '',
                'latitude' => 7.3196389,
                'longitude' => 13.5719884,
                'promoter' => 'SANDJO Emmanuel',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 100,
                'bar_capacity' => 100,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77549990/99768558',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'REST. MENTONG PALACE',
                'description' => '',
                'latitude' => 7.3322358,
                'longitude' => 13.5705014,
                'promoter' => 'KIKI A MENTONG',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 40,
                'bar_capacity' => 40,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99529907/96747766',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'REST. HOTEL FETY',
                'description' => '',
                'latitude' => 7.3360403,
                'longitude' => 13.5677499,
                'promoter' => 'FEUZEU Jonas',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 25,
                'bar_capacity' => 25,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '22252380/74312818',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'REST. HOTEL DE LA GARE',
                'description' => '',
                'latitude' => 7.3223716,
                'longitude' => 13.5645917,
                'promoter' => 'ABDOURAMAN',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 20,
                'bar_capacity' => 20,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99803680/22252217',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'REST. COFFEE SHOP',
                'description' => '',
                'latitude' => 6.9997889,
                'longitude' => 9.5831889,
                'promoter' => 'MOUSSA Mbelé',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 40,
                'bar_capacity' => 40,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '22252471/99827848',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'REST. HOTEL VINA',
                'description' => '',
                'latitude' => 7.3223451,
                'longitude' => 13.5723166,
                'promoter' => 'ALHADJI Ibrahima',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 25,
                'bar_capacity' => 25,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '22036043/77542973',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'RESTAURANT JACQUIE',
                'description' => '',
                'latitude' => 5.8792038,
                'longitude' => 9.0713855,
                'promoter' => 'NGO Mabong Jacqueline',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 100,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99499498',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'RESTAURANT AFRIK’ SAVEUR',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'NGOUTANE Claude Liliane',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 50,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77206251',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'RESTAURANT CONCORDE',
                'description' => '',
                'latitude' => 6.5938246,
                'longitude' => 9.8546334,
                'promoter' => 'ABDULKARIM Sadou',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 40,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77280858/99943273',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'RESTAURANT LE BEGER',
                'description' => '',
                'latitude' => 7.0850933,
                'longitude' => 11.8881482,
                'promoter' => 'PHILOMENE Belobo',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 27,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '75465149',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'RESTAURANT MAGNI',
                'description' => '',
                'latitude' => 7.0868287,
                'longitude' => 11.8880594,
                'promoter' => null,
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 60,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'RESTAURANT DOLCE VITA',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'HALMATA',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 35,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99860865',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'CIRCUIT CLAIRE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'NKOA Mengue Claire',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 40,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '22251767',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'CIRCUIT LA MEDITERRANNEE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'YAHEU Florentine',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 50,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '94862757',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 2,
                'name' => 'RESTAURANT DELFOOD',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => null,
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 50,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 2,
                'name' => 'RESTAURANT CALYPSO',
                'description' => '',
                'latitude' => 6.4649923,
                'longitude' => 12.6178229,
                'promoter' => 'Mme KUIPO',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 60,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '75172547',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 2,
                'name' => 'RESTAURANT CALIFORNIA',
                'description' => '',
                'latitude' => 6.448161,
                'longitude' => 13.2707049,
                'promoter' => 'VILDINA Alphonse',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 45,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '96937616',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 2,
                'name' => 'RESTAURANT Le Bien Etre',
                'description' => '',
                'latitude' => 6.4699091,
                'longitude' => 9.5803081,
                'promoter' => 'BIDIM Barthélemy',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 50,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '94660136',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 2,
                'name' => 'RESTAURANT SANTA Barbara',
                'description' => '',
                'latitude' => 6.4687696,
                'longitude' => 13.2665381,
                'promoter' => 'Me DJOFACK',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 18,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 5,
                'type' => 2,
                'name' => 'RESTAURANT DU LAC',
                'description' => '',
                'latitude' => 7.3381956,
                'longitude' => 5.1293086,
                'promoter' => 'ABDOLAYE',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 40,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 5,
                'type' => 2,
                'name' => 'RESTAURANT CHEZ CHANTAL',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'ABOULM Chantal',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => 10,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99113743',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 3,
                'name' => 'TRANSCAM BOUKAROU',
                'description' => '',
                'latitude' => 7.3106694,
                'longitude' => 13.5725329,
                'promoter' => 'SNHC',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => 80,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99923280',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 3,
                'name' => 'MARHABA NIGHT CLUB',
                'description' => '',
                'latitude' => 7.3196975,
                'longitude' => 13.5722414,
                'promoter' => 'SANDJO Emmanuel',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => 150,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '77549990/99768558',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 3,
                'name' => 'SNACK BAR LA PLAZZA',
                'description' => '',
                'latitude' => 7.3208228,
                'longitude' => 13.5754829,
                'promoter' => 'DABADJI Fouad',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => 80,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '99855151/99527963',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 3,
                'name' => 'SNACK BAR LE SAPHYR',
                'description' => '',
                'latitude' => 7.319954,
                'longitude' => 13.5930835,
                'promoter' => 'FEZEU Jonas',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => 50,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '22252380/74312818',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 3,
                'name' => 'SNACK BAR EPI D’OR',
                'description' => '',
                'latitude' => 7.3217478,
                'longitude' => 13.5742561,
                'promoter' => 'HELOU',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => 40,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '96313131/22166813',
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 3,
                'name' => 'EL PACHA',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'NDOUNGUE Noel',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => 100,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 3,
                'name' => 'WEE GARA',
                'description' => '',
                'latitude' => 6.5304727,
                'longitude' => 12.0240469,
                'promoter' => 'NDJIKA Mbélé',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => 90,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 3,
                'name' => 'CLUB GUINESS',
                'description' => '',
                'latitude' => 7.7682259,
                'longitude' => 15.3450664,
                'promoter' => 'Nguessom',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => 70,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'type' => 3,
                'name' => 'NOBLESSE',
                'description' => '',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'Nguessom',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => 70,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],

            [
                'department_id' => 1,
                'type' => 5,
                'name' => 'SAMA YOYAGES',
                'description' => 'Réservation et achat des billets de train/ Encadrement des pèlerins pour le Hadj',
                'latitude' => 9.3178828,
                'longitude' => 13.4021321,
                'promoter' => 'SAMA YOYAGES',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '23722251702/23796549879 samavoyages01@yahoo.fr',
                'website' => null
            ],
            [
                'department_id' => 1,
                'type' => 5,
                'name' => 'ALDA SARL',
                'description' => 'Location de voitures',
                'latitude' => null,
                'longitude' => null,
                'promoter' => 'SAMA YOYAGES',
                'number_of_stars' => null,
                'number_of_rooms' => null,
                'number_of_beds' => null,
                'restaurant_capacity' => null,
                'bar_capacity' => null,
                'conference_room_capacity' => null,
                'capacity' => null,
                'parking' => null,
                'is_public' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => '74864747/99468353 aldasarl@yahoo.fr',
                'website' => null
            ],
        ]);
    }
}
