<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $openingHours0 = json_encode([
            "Monday" => ["open" => "08:00", "close" => "18:00"],
            "Tuesday" => ["open" => "08:00", "close" => "18:00"],
            "Wednesday" => ["open" => "08:00", "close" => "18:00"],
            "Thursday" => ["open" => "08:00", "close" => "18:00"],
            "Friday" => ["open" => "08:00", "close" => "18:00"],
            "Saturday" => ["open" => "10:00", "close" => "16:00"],
            "Sunday" => ["open" => "10:00", "close" => "16:00"],
        ]);
        $openingHours1 = json_encode([
            "Monday" => ["open" => "00:00", "close" => "23:59"],
            "Tuesday" => ["open" => "00:00", "close" => "23:59"],
            "Wednesday" => ["open" => "08:00", "close" => "18:00"],
            "Thursday" => ["open" => "08:00", "close" => "20:00"],
            "Friday" => ["open" => "08:00", "close" => "20:00"],
            "Saturday" => ["open" => "10:00", "close" => "16:00"],
            "Sunday" => null,
        ]);
        DB::table('sites')->insert([
            [
                'department_id' => 1,
                'name' => 'Chutes de la Vina',
                'description' => 'Chute d’une hauteur de 30m',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'A tout moment',
                'access_means' => 'Accessible à moto et à véhicule',
                'offered_service' => 'Ecotourisme',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Chutes de Tello',
                'description' => 'Chutes très spectaculaires d’une hauteur de 40 m formant une grotte avec le rocher en forme d’un arc de cercle sur lequel la rivière Tello prend son point de chute',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Toute saison',
                'access_means' => 'Accessible à moto et à véhicule',
                'offered_service' => 'Ecotourisme',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Chutes de Koudini',
                'description' => 'L’eau a une hauteur de chute d’environ 40 m et tombe d’une énorme table rocheuse d’environ 50m de diamètre',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'A tout moment',
                'access_means' => 'Accessible à moto et à pied',
                'offered_service' => 'Ecotourisme',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Chutes de Bini',
                'description' => 'Chute très magnifique près de 40 m de hauteur',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'A tout moment',
                'access_means' => 'Accessible à moto et à pied',
                'offered_service' => 'Ecotourisme',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Chutes de Waka-Bodo',
                'description' => 'Chute ayant des grosses langues d’eau coulant sur des rochers dispersés en escalier',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Novembre - Avril',
                'access_means' => 'Accessible à moto et à pied',
                'offered_service' => 'Ecotourisme',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Lac Tison',
                'description' => 'Lac de cratère particulièrement encaissé aux sensations fortes, véritable attraction touristique',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Toute saison',
                'access_means' => 'Accessible à pied, à moto et à véhicule',
                'offered_service' => 'Ecotourisme, Tourisme de vision',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Lac Mballang',
                'description' => 'Lac de cratère dont la rivière stabilise son niveau',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Toute saison',
                'access_means' => 'Accessible à moto et à pied',
                'offered_service' => 'Ecotourisme',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Lac de Wakwa',
                'description' => 'Lac de barrage d’environ 12ha dans l’enceinte de l’IRAD de Wakwa. Poissonneux, ce lac est régulièrement fréquenté par les canards sauvages et atteint 40 m de profondeur par endroits, il sert également d’abreuvoir au bétail',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Toute saison',
                'access_means' => 'Accessible à pied, à moto et à véhicule',
                'offered_service' => 'Ecotourisme',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Lac de Dang',
                'description' => 'Vaste étendue d’eau, poissonneux et présence de plusieurs espèces aviaires et envahie de mauvaises herbes.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Toute saison',
                'access_means' => 'Accessible à pied, à moto et à véhicule mais non aménagé',
                'offered_service' => 'Ecotourisme',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Lac Darang',
                'description' => 'Lac très poissonneux',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'A tout moment',
                'access_means' => 'Accessible à moto et à véhicule',
                'offered_service' => 'Ecotourisme',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Ranch de Ngaoundaba',
                'description' => 'Ce ranch est situé à une altitude de 1 300 m dans un parc au bord du lac de 2ha environ, très profond et très poissonneux. Structure d’accueil très reposant par sa localisation et son architecture originelle, doté d’un grand verger, d’un lac de cratère et d’une salle d’exposition des trophées de chasse. Présence de plusieurs espèces aviaires.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Toute saison',
                'access_means' => 'Accessible à moto et à véhicule',
                'offered_service' => 'Tourisme culturel, pirogue sur le lac, randonnée et découverte',
                'cultural_info' => 'Site pour le moment fermé.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Ranch pastoral de Goundjel',
                'description' => 'Ranch constitué d’un vaste pâturage où évoluent les bœufs par millier et à perte de vue.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Toute saison',
                'access_means' => 'Accessible à moto et à véhicule',
                'offered_service' => 'Agro tourisme',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Lamidat de Ngaoundéré',
                'description' => 'Chefferie traditionnelle dont l’architecture est composée des cases rondes au toit en toupie et faits de chaume.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => 'Tourisme culturel, fantasia, architecture exceptionnelle, sons de tambours et trompes',
                'cultural_info' => 'La population autochtone n’entre pas avec les chaussures au lamidat sauf les étrangers et les Autorités Administratives. Sortie en parade du Lamido les vendredis et jours de fête.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Village Idool',
                'description' => 'Village touristique au quartier en damier créé en 1968 avec une imposante chefferie construite selon la tradition peulh avec un climat doux et des arbres fruitiers en abondance, architecture traditionnelle remarquable, présence d’un lac artificiel en forme du Cameroun.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => 'Tourisme culturel',
                'cultural_info' => 'L’hospitalité légendaire engendre la visite des hommes de marque (Tombal Bay, Ahmadou Ahidjo etc…)',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Falaise de Mbé',
                'description' => 'Site très reposant situé à une altitude permettant d’avoir une bonne vue panoramique sur la plaine de Mbé, présence des singes.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => 'Site aménagé en 2008 par le MINTOUR. Présence d’un bar restaurant.',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Grotte de MBang',
                'description' => 'Grottes entourées d’arbres en forme des boukarous.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Novembre - Avril',
                'access_means' => 'Accessible mais non aménagé',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Grotte de Ngan-ha',
                'description' => 'Lieu de refuge des Mboums lors des guerres de résistance.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Novembre - Avril',
                'access_means' => 'Accessible',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Grottes Mayo-Djabo',
                'description' => 'Grotte qui combine avec une chute qui porte le même nom et haut de près de 30 m.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Novembre - Avril',
                'access_means' => 'Accessible mais non aménagé',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Mont Ngaoundéré',
                'description' => 'Montagne qui porte le nom de la ville en langue Mboum qui signifie la montagne au nombril. Il est le gardien de la ville de Ngaoundéré.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => 'Tourisme sportif',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Mont Ngan-ha',
                'description' => 'Existence de plusieurs grottes où on retrouve des objets d’art. Véritable sanctuaire des populations Mboum de Ngan-ha.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Novembre - Avril',
                'access_means' => 'Accès difficile',
                'offered_service' => 'Ecotourisme, Trekking',
                'cultural_info' => 'Refuge pour le peuple Mboum lors de la période coloniale.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Sources thermo-minérales de Laouré',
                'description' => 'Au pied de la chute de la Vina, source d’eau chaude de 35°C, fortement minéralisée en sodium, calcium et magnésium.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Campement Faro-coron',
                'description' => 'Situé dans une zone très giboyeuse où campent les orpailleurs.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Arbre Centenaire Litahi',
                'description' => 'Grand arbre situé en plein centre ville de Ngaoundéré.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => null,
                'cultural_info' => 'Les foulbés et les Mboum ont signé sous cet arbre de plus de 100ans, un pacte pour le partage du pouvoir au Lamidat et pour lequel le Lamido doit automatiquement être de race Mboum et Foulbé pour régner.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 1,
                'name' => 'Festival Mbor-Yanga',
                'description' => 'Manifestation touristico-culturelle au cours de laquelle le Bélaka ou Chef Supérieur Mboum entre en communion avec son peuple pour se souvenir de leur passé glorieux en célébrant un culte aux ancêtres Mboum à travers les activités telles que la sortie des objets royaux, la sortie solennelle du Bélaka, les activités culturelles, les excursions, l’exposition d’objets d’art.',
                'latitude' => 7.3215634,
                'longitude' => 13.5793109,
                'visite_periode' => 'Tous les deux ans',
                'access_means' => 'Accessible',
                'offered_service' => 'Tourisme culturel',
                'cultural_info' => 'Festival restauré en 2002 par le 42ème « Bélaka » ou chef supérieur Mboum.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Grottes Mont-DJIM',
                'description' => 'Enorme colline rocheuse située à 5 km de Galim-Tignère. Cette colline fût habitée par les Nyem-Nyem de 1800 à 1945. Grâce à l’accès difficile à cause du relief très accidenté et sa grotte à plusieurs compartiments, les Nyem-Nyem ont pu résister aux Allemands et aux Foulbés sur cette colline pendant la guerre de résistance. Sur ce Mont, on y retrouve à nos jours les traces de la civilisation de ce peuple guerrier, la tombe des cinq chefs morts pendant les guerres, les fondations, le lieu d’exécution des condamnés à mort, les morceaux de canaris, source d’eau ayant les vertus thérapeutiques, etc.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible Novembre - Mars',
                'access_means' => 'Accessible',
                'offered_service' => 'Safari photo, découverte historique',
                'cultural_info' => 'La particularité de ce site est que c’est un milieu considéré comme étant sacré pour son peuple qui organise une fête rituelle chaque fin d’année en mémoire des ancêtres qui sont morts pendant les guerres de résistance. Au cours de cette fête, les Nyem-Nyem rendent hommage à la tombe collective des cinq chefs morts pendant la guerre.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Grottes Damougaré',
                'description' => 'Cavité naturelle d’une superficie de 300 m² de forme irrégulière. Cette grotte fût autrefois habitée par les koutines et servait de lieu de refuge pour ce peuple lors des guerres tribales et la colonisation Foulbé. Cet énorme rocher qui abrite la grotte Damougaré a une hauteur d’au moins 100 m avec un pourtour d’environ 1800 m. L’agencement des particules des pierres de dimensions variables laisse au visiteur l’occasion d’apprécier cette architecture naturelle. Présence de petites antilopes et des colombes à manteaux blancs. Présence d’une galerie forestière associée aux plantes grasses montagnardes.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible Novembre - Mars',
                'access_means' => 'Accessible',
                'offered_service' => 'Tourisme de vision, safari photo, découverte historique',
                'cultural_info' => 'Cette grotte prend le nom de Damougaré qui signifie « porte » en foulfouldé à cause de l’existence de deux ouvertures dont la plus grande située sur la face antérieure et visible à partir de l’axe centrale reliant Tignère à Ngaoundéré, servait de poste de contrôle des ennemis. La petite ouverture située sur la face postérieure constitue l’entrée.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Mont Yangaré',
                'description' => 'Pittoresque de par sa hauteur.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible à pied et à moto',
                'access_means' => 'Accessible',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Mont DJINGA',
                'description' => 'Massif montagneux d’une hauteur de 1710 m. Cette montagne présente un intérêt particulier tant pour sa faune que pour sa flore. Actuellement délimité par la SODEPA pour l’élevage du bétail. Ce site est d’une beauté pittoresque. Sa flore est celle des prairies d’altitude de la grande dorsale de l’Adamaoua, à l’herbe rase et aux plantes grasses montagnardes. Cette chaîne montagneuse est en outre habitée par les lions, panthères, buffles, hippotragus, corne de Buffon, phacochères et autres petites antilopes. À l’extrême droite de ce massif s’étend une vaste plaine couverte par un tapis herbacé à prédominance andropogons gyaneus. Ce massif semble être l’une des rares oasis à avoir pu échapper au dépérissement général, ce qui fait que ce site constitue à l’heure actuelle un échantillon de ce qu’a pu être la nature autrefois.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible Novembre - Juin',
                'access_means' => 'Accessible à pied',
                'offered_service' => 'Excursion, alpinisme',
                'cultural_info' => 'Site d’une beauté pittoresque.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Mont Ngaoudja',
                'description' => 'Mont ayant un potentiel indéniable. Longue chaîne montagneuse et savane boisée.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => 'Escalade en saison sèche et prise de vues',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Mont Guenfalabo',
                'description' => 'Potentiel éco-touristique indéniable avec buffles, antilopes, phacochères.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => 'Randonnée pédestre.',
                'cultural_info' => 'Chaîne montagneuse présentant une fière allure.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Hausséré caé (Pilonites)',
                'description' => 'Existence des pierres monolithiques.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Source thermale de WOULDE',
                'description' => 'Elle est située à une centaine de mètres au nord du pont sur le Mayo Wouldé. Elle est une émergence d’eau chaude dont la température avoisine les 70°C. Peut faire cuire l’œuf. Présence d’antilopes et de porc-épics.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => null,
                'cultural_info' => 'L’eau sert des remèdes traditionnels, guérit le rhumatisme, riche en bicarbonate et en sodium.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Falaise de SADECK',
                'description' => 'Rupture de pente entre le plateau et la plaine PERE. Longue de 4 km, la route qui sillonne cette forte pente comporte des visages assez dangereux. Lorsqu’il fait beau temps, la visite de la falaise Sadeck offre une vue panoramique et permet d’observer de nombreuses chaînes montagneuses qui entourent la plaine PERE. Savane boisée, quelques animaux résistent à l’assaut des braconniers.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => 'Tourisme de vision',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Wamdop',
                'description' => 'Berge du Déo, très sablonneux et par endroit ayant des pierres polies, vaste étendue du cours d’eau Déo. Plaine plate et chaude en janvier, février, mars et avril. Faune riche, lions, buffles… savane boisée, eau de forage.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => 'Tourisme de vision',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'TCHABAL MBABO',
                'description' => 'Beau paysage, faune riche et variée, buffles, lions, antilopes, phacochères, site d’une beauté pittoresque.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible Novembre - Mars',
                'access_means' => 'Accès difficile',
                'offered_service' => 'Ecotourisme, randonnée pédestre ou à cheval',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Gorge de TEGPACK et Bemlari',
                'description' => 'Existence d’un pont de singe historique, flore riche en plusieurs espèces.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible mais non aménagé, Novembre - Mars',
                'access_means' => 'Accessible mais non aménagé',
                'offered_service' => null,
                'cultural_info' => 'Vastes étendues plates abondantes et variées, savane arborée.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Grottes de Mayo-Mbaggou',
                'description' => 'Caverne à l’intérieur d’une grande pierre qui servait de case de passage des chasseurs.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => null,
                'access_means' => null,
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Chute de Tagouri',
                'description' => 'Potentiel éco-touristique.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible mais non aménagé, Novembre - Mars',
                'access_means' => 'Accessible mais non aménagé',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Lac Mbanjen',
                'description' => 'Lac à couleur d’arc-en-ciel.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible mais non aménagé, Novembre - Mars',
                'access_means' => 'Accessible mais non aménagé',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'SODEPA Ranch El Hadj Abdoullahi',
                'description' => 'Existence d’un parc d’insémination artificielle, présence d’une gigantesque autruche.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible mais non aménagé, Toute l’année',
                'access_means' => 'Accessible mais non aménagé',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Ranch de la SODEPA',
                'description' => 'Société parapublique chargée de la production animale, ce ranch couvre une superficie totale de 40 000 ha, pratique les méthodes modernes d’élevage, produit de bœufs de boucherie moderne et compte actuellement 16 000 têtes de bovins. Réserve faunique riche et variée.',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Accessible toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => 'Tourisme de vision, safari-photo',
                'cultural_info' => 'Savane arborée.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 2,
                'name' => 'Festival Nyem-Nyem',
                'description' => 'Manifestation touristicoculturelle qui vise à commémorer la victoire du peuple Nyem Nyem sur les colonisateurs allemands à travers l’ascension du Mont Djim et l’exhibition culturelle (danse traditionnelle, sketches, fantasia, exposition d’objets d’art).',
                'latitude' => 6.1234567,
                'longitude' => 12.6543210,
                'visite_periode' => 'Biennal',
                'access_means' => null,
                'offered_service' => 'Tourisme culturel et écotourisme',
                'cultural_info' => 'La particularité de ce festival est de présenter aux visiteurs la danse traditionnelle guerrière exécutée par les hommes équipés d’armes ancestrales et la danse des récoltes appelées « Nvouri ».',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Chutes de lancrénon',
                'description' => 'Potentiel éco touristique de 80m d’hauteur, fait frontière avec la RCA.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Novembre - Mars',
                'access_means' => 'Accessible',
                'offered_service' => 'Ecotourisme',
                'cultural_info' => 'Pour chaque visite, il faut l’avis du Chef de Village Yamba.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Chutes de Kombo Laka',
                'description' => 'Site pittoresque.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Danse Zabolo, exploitation minière (or, Diamant)',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Chutes de Gunbela',
                'description' => 'Paysage florissant.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Vue panoramique, Randonnée et pic-nic',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Cascades de Gbembarang',
                'description' => 'Hauteur 30m.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute l’année',
                'access_means' => 'Accessible',
                'offered_service' => 'Site pittoresque',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Lac de Nandéké',
                'description' => 'Lac vidé de ses eaux suite à l’effondrement de la digue, proximité avec les villages.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Randonnée pédestre, jogging',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Lac Mbarang',
                'description' => 'Sanctuaire à oiseaux, pêche sportive, proximité avec les villages.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Tourisme sportif',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Lac de Gbaingbaya',
                'description' => 'Lac inexploité depuis 50ans.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Site éco touristique',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Etangs de Karnou',
                'description' => 'Randonnée et pêche sportive, sanctuaire à oiseaux.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Tourisme sportif',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Source de Logone et de la Sanaga',
                'description' => 'Source naturelle formant le fleuve Djérem qui se jette dans la Sanaga et le fleuve Mbéré qui se jette dans le logone.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Tourisme historique',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Source de miel',
                'description' => 'Technique de production et dégustation.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Agrotourisme',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Paysage Katyl-foulbé',
                'description' => 'Production du miel.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Agrotourisme',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Failles de Fada',
                'description' => 'Site dangereux, glissement de terrains fréquents.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Trekking',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Mont Ngolo',
                'description' => 'Montagne intéressante pour le trekking.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Trekking',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Mont Ganga',
                'description' => 'Mont où la ville tire son nom.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Excursion jogging',
                'cultural_info' => 'Trekking',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Mont Ngaoui',
                'description' => 'Transaction pastorale vers le Gabon, le Tchad, le Nigéria, grand marché frontalier.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Grottes et chutes de Kombo-laka',
                'description' => 'Site pittoresque, exploitation minière artisanale.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Safari photo',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Grotte de Mboula',
                'description' => 'Centre originel de la danse initiatique Labi Gbaya.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Safari photo',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Grotte de Wah (Dir)',
                'description' => 'Chasse sportive aux pythons.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Ecotourisme, tourisme cynégétique',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Parc National de la vallée du Mbéré',
                'description' => 'Crée en 2004 ; conservation de la biodiversité : intérêts scientifiques, présence de plusieurs espèces animales et aviaires.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Ecotourisme, tourisme cynégétique',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Musée de Djohong',
                'description' => 'Seule musée de la Région regorgeant plusieurs objets d’art.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Histoire du Lamidat',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Site Archéologique',
                'description' => 'Recherche archéologique.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Mouvement migratoire',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 3,
                'name' => 'Pierre mystérieuse et sacrée le Kaazon',
                'description' => 'Recherche culturelle.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible Toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Histoire du Lamidat',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Lac MBELLA ASSOM',
                'description' => 'Lac de cratère de forme irrégulière ; présence des hippopotames et caïmans.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible En toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Prise de vues et sport nautique ; pêche à la ligne',
                'cultural_info' => 'Très légendaire pour les Mboum.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Lac PANGYERE',
                'description' => 'Lac naturel de 90ha environ de forme irrégulière, poissonneux.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible En toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Prise de vue et sport nautique ; pêche à la ligne',
                'cultural_info' => 'Très légendaire pour les Bouté.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Lac artificiel de MBAKAOU',
                'description' => 'Grande retenue d’eau. Très poissonneuse.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'En toute saison',
                'access_means' => 'Route praticable par tous les moyens de locomotion',
                'offered_service' => 'Tourisme de vision, pêche sportive',
                'cultural_info' => 'Réserve pour alimenter le barrage d’Edéa construit en 1967.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Lacs « JUMEAU » de GASSOL',
                'description' => 'Lac de cratère de forme irrégulière ; présence des hippopotames et caïmans.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible aux engins à 2 roues ou à pied',
                'access_means' => 'Accessible',
                'offered_service' => 'Tourisme de vision, pêche à la ligne',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Lac SOTE',
                'description' => 'Lac de cratère, situé au sommet du Mont SOTE. Présence des hippopotames.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'A tout moment',
                'access_means' => 'Accès difficile sur 15 km.',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Lac Taparé',
                'description' => 'Lac de cratère, très poissonneux, présence d’hippopotames.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'A tout moment',
                'access_means' => 'Accessible aux engins à deux roues',
                'offered_service' => 'Tourisme de vision',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Lac Pang',
                'description' => 'Lac de cratère, présence d’hippopotames.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'A tout moment',
                'access_means' => 'Accessible aux engins à deux roues',
                'offered_service' => 'Tourisme de vision',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Lac FaouRoum',
                'description' => 'Lac naturel de forme irrégulière, très poissonneux.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'A tout moment',
                'access_means' => 'Piste accessible à vélo/motocyclette et à pirogue',
                'offered_service' => 'Tourisme de vision et pêche à la ligne',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Lac Madjoing',
                'description' => 'Lac naturel d’une très belle vue.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible En toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Photos oiseaux de diverses espèces, sports nautiques',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Chute de la Carrière et de Miyéré',
                'description' => 'Chute en cascade des eaux du fleuve Djerem.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible En toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Prise de vues',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Mont Ngaoundal',
                'description' => 'Hauteur : 1300 m, chaîne montagneuse, plus haut sommet du Département.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible En toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Prise de vues, escalade et découvertes',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Grotte SOTTE',
                'description' => 'Refuge du peuple Vouté lors de la pénétration coloniale et de l’invasion Foulbé.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'A tout moment',
                'access_means' => 'Randonnée à cheval',
                'offered_service' => 'Prise de vues, exploration de la grotte',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Réserve du Mbam et Djerem',
                'description' => 'Abrite diverses espèces d’animaux et d’oiseaux : éléphants, chimpanzés et une flore de grande beauté.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible mais reste à viabiliser',
                'access_means' => 'Accessible',
                'offered_service' => 'Tourisme de vue et chasse sportive sur autorisation du conservateur',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Tranchée',
                'description' => 'Tranchées creusées à la main au 19e siècle formant une ceinture de sécurité autour de la ville.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible A tout moment',
                'access_means' => 'Accessible',
                'offered_service' => 'Reflet d’un passé guerrier, prise de vues et exploration du lieu',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Barrage de MBAKAOU',
                'description' => 'Grande retenue d’eau très poissonneuse.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible A tout moment',
                'access_means' => 'Accessible',
                'offered_service' => 'Prise de vues, escalade et exploration du barrage après avis du responsable',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Palais du Lamido de Tibati',
                'description' => 'Résidence du Lamido, véritable musée.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible A tout moment',
                'access_means' => 'Accessible',
                'offered_service' => 'Prise de vues et découverte du lieu et objets d’art traditionnels après avis des Autorités',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Palais des Chefs de Canton',
                'description' => 'Résidences des Chefs desdits Cantons qui tiennent lieu de musées d’arts traditionnels.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible A tout moment',
                'access_means' => 'Accessible',
                'offered_service' => 'Prise de vues et découverte du lieu et objets d’art traditionnels après avis des Autorités',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Festival « MAKATA »',
                'description' => 'Célébration des rites traditionnels du peuple Mboum de Mbella Assom.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Se tient tous les 2 ans en décembre généralement',
                'access_means' => 'Accessible',
                'offered_service' => 'Manifestation touristicoculturelle',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 4,
                'name' => 'Mosquée, Eglise Protestante, Eglise Catholique',
                'description' => 'Grande bâtisse servant de lieu de culte musulman, protestant et catholique.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'Accessible A tout moment',
                'access_means' => 'Accessible',
                'offered_service' => 'Prise de vue, exploration du lieu après avis du chef religieux',
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
        ]);

// Insertion for Département du Mayo Banyo
        DB::table('sites')->insert([
            [
                'department_id' => 5,
                'name' => 'Mont Djoumbal',
                'description' => 'Refuge des populations pendant les guerres coloniales. Grottes pittoresques aménagées par les Allemands.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'En toute saison',
                'access_means' => 'Accessible',
                'offered_service' => 'Trekking',
                'cultural_info' => 'On retrouve les vestiges Allemandes telles le vieil aérodrome, le champ de tire, la prison, l’observatoire.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 5,
                'name' => 'Lac BEINGOU',
                'description' => 'Lac de cratère très poissonneux.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'En toute saison',
                'access_means' => 'Accès facile.',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 5,
                'name' => 'Lac SOME',
                'description' => 'Lac poissonneux et présence des hippopotames (vers 9 heures du matin).',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'En toute saison',
                'access_means' => 'Accessible',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 5,
                'name' => 'Lac MAYAN',
                'description' => 'Lac poissonneux et présence des hippopotames.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'En toute saison',
                'access_means' => 'Accessible',
                'offered_service' => null,
                'cultural_info' => null,
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 5,
                'name' => 'Barrage de la Mappé',
                'description' => 'Rupture entre le plateau de l’Adamaoua et la plaine du Noun.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'En toute saison',
                'access_means' => 'Accès facile',
                'offered_service' => null,
                'cultural_info' => 'On retrouve des expatriés et des nationaux.',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
            [
                'department_id' => 5,
                'name' => 'Falaise de Banyo ou YIMBERE',
                'description' => 'Rupture entre le plateau de l’Adamaoua et la plaine du Noun.',
                'latitude' => 5.1234567,
                'longitude' => 13.6543210,
                'visite_periode' => 'En toute saison',
                'access_means' => 'Accessible',
                'offered_service' => null,
                'cultural_info' => 'La falaise s’étend le long de la route Banyo-Bankim',
                'ticket_price' => null,
                'image' => 'https://fakeimg.pl/300/',
                'contact_info' => null,
                'website' => null
            ],
        ]);
    }
}
